## You should create one R script called run_analysis.R that does the following. 
## Merges the training and the test sets to create one data set.
## Extracts only the measurements on the mean and standard deviation for each measurement. 
## Uses descriptive activity names to name the activities in the data set
## Appropriately labels the data set with descriptive variable names. 
## From the data set in step 4, creates a second, independent tidy data set with the average 
## of each variable for each activity and each subject.

## First set the working directory to the one where all my files are stored
setwd("~/Google Диск/Coursera/datasciencecoursera/gettingdata/course2")

## Read all needed data from files:

## Features and activity labels
features <- read.table('./raw_data/features.txt', header=FALSE)
activities <- read.table('./raw_data/activity_labels.txt', header=FALSE)

## Training data and test data
subject_Train <- read.table('./raw_data/train/subject_train.txt', header=FALSE)
x_Train <- read.table('./raw_data/train/X_train.txt', header=FALSE)
y_Train <- read.table('./raw_data/train/y_train.txt', header=FALSE)
subject_Test <- read.table('./raw_data/test/subject_test.txt', header=FALSE)
x_Test <- read.table('./raw_data/test/X_test.txt', header=FALSE)
y_Test <- read.table('./raw_data/test/y_test.txt', header=FALSE)

## Task 1
## Now let's merge the train and test data together for subjects, X and Y data sets
## Simply binding rows
subject_Data <- rbind(subject_Train, subject_Test)
x_Data <- rbind(x_Train, x_Test)
y_Data <- rbind(y_Train, y_Test)

## Task 2
## Extracting only the measurements on the mean and standard deviation for each measurement

## Get list of needed cols in features dataset: mean and st.dev.
neededcols <- grep(".*-mean.*|.*-std.*", features[,2])

## Leaving only needed cols
x_Data <- x_Data[, neededcols]

## Task 3
## Replacing values in y_Data with the corresponding names of activities and naming the column
y_Data[ ,1] <- activities[y_Data[ ,1], 2]

## Task 4
## Naming the columns of the data
names(x_Data) <- features[neededcols, 2]
names(y_Data) <- "Activity"
names(subject_Data) <- "Subject"

## Binding all data together
allData <- cbind(subject_Data, y_Data, x_Data)

## Task 5
## Computing the summary stats of allData by applying mean function to subsets of activity & subject
tidyData <- aggregate(allData, by=list(activity = allData$Activity, subject=allData$Subject), mean)

## Removing excessive columns generated by aggregation
tidyData$Subject <- NULL
tidyData$Activity <- NULL

## Writing it to the text file
write.table(tidyData, './tidyData.txt', row.names=FALSE, sep='\t');
